sonar.projectKey=jest-sonarqube
sonar.projectName=jest-sonarqube
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=https://super-giggle-jj947pvwr657hqpqx-9000.app.github.dev/
# Pass token via env: 
SONAR_TOKEN=sqp_22c9eacd1b3ce5a38e56da4c21e4bce5746862e7

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8