sonar.projectKey=jest-sonarqube
sonar.projectName=jest-sonarqube
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.host.url=https://didactic-xylophone-97wq5gr46v6w36xr-9000.app.github.dev/
# Pass token via env: 
SONAR_TOKEN=sqp_ad9040842747841791ad84d4d502bef23a75227a

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8