- name: SonarQube Scan 
  uses: SonarSource/sonarqube-scan-action@v5
  env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://didactic-xylophone-97wq5gr46v6w36xr-9000.app.github.dev
        with:
          # The args MUST be indented further than 'with'
          args: >
            -Dsonar.projectKey=asfasdfasfa
            -Dsonar.projectName=asfasdfasfa
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.inclusions=src/**/*.ts,src/**/*.tsx
            -Dsonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/setupTests.ts,src/main.tsx,node_modules/**,dist/**,coverage/**
            -Dsonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.tsconfigPath=tsconfig.json
